### ISSUE TITLE
Флаг активации алисы

### ISSUE THREAD

**Issue by wisesokol** [alryaz/hass-component-yandex-smart-home#5]
Добрый день.
Есть ли возможность вывести в HA флаг активации Алисы? Я хочу глушить звук телевизора (ir remote) когда веду диалог с Алисой. Пока есть идея привязать аппаратно esp8266 (esphome) к диодам станции. Диод активирован- HA активирует на телеке без шумный режим на 5-10 секунд.

**Comment by panferovaleksey** [comment]
С этим вопросом вам сюда - https://github.com/AlexxIT/YandexStation

**Comment by wisesokol** [comment]
Спасибо. Уже обкатываю.
